// <auto-generated />
using System;
using Akatsuki_ThiGiuaKy.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Akatsuki_ThiGiuaKy.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.DatVe", b =>
                {
                    b.Property<int>("MaDatVe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaLichChieuPhim")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianDat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDatVe");

                    b.HasIndex("MaLichChieuPhim");

                    b.ToTable("DatVes");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.LichChieuPhim", b =>
                {
                    b.Property<int>("MaLichChieuPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaPhim")
                        .HasColumnType("int");

                    b.Property<int>("MaRap")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianChieu")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichChieuPhim");

                    b.HasIndex("MaPhim");

                    b.HasIndex("MaRap");

                    b.ToTable("LichChieuPhims");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.Phim", b =>
                {
                    b.Property<int>("MaPhim")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenPhim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThoiLuong")
                        .HasColumnType("int");

                    b.HasKey("MaPhim");

                    b.ToTable("Phims");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.Rap", b =>
                {
                    b.Property<int>("MaRap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SoChoTrong")
                        .HasColumnType("int");

                    b.Property<string>("TenRap")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaRap");

                    b.ToTable("Raps");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.DatVe", b =>
                {
                    b.HasOne("Akatsuki_ThiGiuaKy.Entities.LichChieuPhim", "LichChieuPhim")
                        .WithMany("DatVes")
                        .HasForeignKey("MaLichChieuPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichChieuPhim");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.LichChieuPhim", b =>
                {
                    b.HasOne("Akatsuki_ThiGiuaKy.Entities.Phim", "Phim")
                        .WithMany("LichChieuPhims")
                        .HasForeignKey("MaPhim")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Akatsuki_ThiGiuaKy.Entities.Rap", "Rap")
                        .WithMany("LichChieuPhims")
                        .HasForeignKey("MaRap")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Phim");

                    b.Navigation("Rap");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.LichChieuPhim", b =>
                {
                    b.Navigation("DatVes");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.Phim", b =>
                {
                    b.Navigation("LichChieuPhims");
                });

            modelBuilder.Entity("Akatsuki_ThiGiuaKy.Entities.Rap", b =>
                {
                    b.Navigation("LichChieuPhims");
                });
#pragma warning restore 612, 618
        }
    }
}
